import { Bike, Car, CarFront, Package, Bus } from "lucide-react";

export const rideOptions = [
    {
        slug: "bike",
        title: "Bike",
        image: "/images/images.jpg",
        icon: Bike,
        rate: "₹6/km",
        eta: "2 min",
        fareRange: "₹40 - ₹70",
        tagline: "Quick and affordable for solo trips",
    },
    {
        slug: "car-economy",
        title: "Car Economy",
        image: "/images/download.jpg",
        icon: Car,
        rate: "₹11/km",
        eta: "4 min",
        fareRange: "₹90 - ₹140",
        tagline: "Comfortable AC rides at low fares",
    },
    {
        slug: "car-premium",
        title: "Car Premium",
        image: "/images/download (1).jpg",
        icon: CarFront,
        rate: "₹18/km",
        eta: "5 min",
        fareRange: "₹150 - ₹220",
        tagline: "Premium sedans for a smooth ride",
    },
    {
        slug: "courier",
        title: "Courier",
        image: "/images/download (3).jpg",
        icon: Package,
        rate: "₹8/km",
        eta: "6 min",
        fareRange: "₹50 - ₹90",
        tagline: "Fast package delivery across the city",
    },
    {
        slug: "rickshaw",
        title: "Rickshaw",
        image: "/images/download (2).jpg",
        icon: Bus,
        rate: "₹7/km",
        eta: "3 min",
        fareRange: "₹35 - ₹60",
        tagline: "Budget-friendly rides for short distances",
    },
];